[package]
name = "brc"
version = "0.0.1"
edition = "2021"
rust-version = "1.81"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brl = { path = "../br_lib" }
log = "0.4"
env_logger = "0.11.3"
